version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
            - ./code:/var/www
        links:
            - php
            - mysql

    node:
        build: docker/node
        container_name: node
        volumes:
            - ./code:/var/www
        depends_on:
            - php

    php:
        build: docker/php
        container_name: php-fpm
        volumes:
            - ./code:/var/www
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        user: "1000:50"
        command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/confi/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        container_name: mysql
        environment:
            MYSQL_DATABASE: rating
            MYSQL_ROOT_PASSWORD: root