version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ../code:/var/www/rating/
            - ./nginx/logs:/var/log/nginx/
        links:
            - php

    php:
        build: ./php
        container_name: php-fpm
        volumes:
            - ../code:/var/www/rating/